openapi: 3.0.0
info:
  title: Server Manager Service
  description: |-
    Define and control your servers with these routes.
  version: 0.1.0
externalDocs:
  description: GitHub
  url: https://github.com/Zane-T-Rice/server-manager-service
tags:
  - name: servers
    description: The root of managing and configuring your Servers
  - name: ports
    description: Manage a Server's Ports
  - name: volumes
    description: Manage a Server's Volumes
  - name: environmentVariables
    description: Manage a Server's EnvironmentVariables
  - name: files
    description: Manage a Server's build Files
paths:
  /servers:
    post:
      tags:
        - servers
      summary: Create a new server
      operationId: createServer
      requestBody:
        $ref: "./servers/serverRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./servers/serverResponse.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    get:
      tags:
        - servers
      summary: Get all Servers
      operationId: getServers
      parameters:
        - in: query
          name: isUpdatable
          schema:
            type: boolean
          description: filter results based on if a server is updatable or not
      responses:
        "200":
          $ref: "./servers/serverArrayResponse.yaml"
        "404":
          $ref: "./servers/errors/serverNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
  /servers/{serverId}:
    get:
      tags:
        - servers
      summary: Get a Server by id
      operationId: getServer
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./servers/serverResponse.yaml"
        "404":
          $ref: "./servers/errors/serverNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    patch:
      tags:
        - servers
      summary: Patch a Server by id
      operationId: patchServer
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      requestBody:
        $ref: "./servers/serverRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./servers/serverResponse.yaml"
        "404":
          $ref: "./servers/errors/serverNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    delete:
      tags:
        - servers
      summary: Delete a server by id
      operationId: deleteServer
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./servers/serverResponse.yaml"
  /servers/{serverId}/complete:
    get:
      tags:
        - servers
      summary: Get a complete Server by id
      description: A complete Server will have all related resources hydrated on to the response.
      operationId: getServerComplete
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./servers/serverCompleteResponse.yaml"
        "404":
          $ref: "./servers/errors/serverNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
  /servers/{serverId}/restart:
    post:
      tags:
        - servers
      summary: Restart a Server by id
      operationId: restartServer
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./servers/serverResponse.yaml"
        "404":
          $ref: "./servers/errors/serverNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
  /servers/{serverId}/update:
    post:
      tags:
        - servers
      summary: Update a Server by id
      description: This is for rebuilding containers to bring them fully up to date. If you are trying to patch the configuration of a server, use the PATCH /servers/{serverId} route instead.
      operationId: updateServer
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./servers/serverCompleteResponse.yaml"
        "404":
          $ref: "./servers/errors/serverNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
  /servers/{serverId}/ports:
    post:
      tags:
        - ports
      summary: Create a new port
      operationId: createPort
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      requestBody:
        $ref: "./ports/portRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./ports/portResponse.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    get:
      tags:
        - ports
      summary: Get Ports of Server
      operationId: getPorts
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./ports/portArrayResponse.yaml"
        "404":
          $ref: "./ports/errors/portNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
  /servers/{serverId}/ports/{portId}:
    get:
      tags:
        - ports
      summary: Get a Port by id
      operationId: getPort
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/portIdInPath.yaml"
      responses:
        "200":
          $ref: "./ports/portResponse.yaml"
        "404":
          $ref: "./ports/errors/portNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    patch:
      tags:
        - ports
      summary: Update a Port by id
      operationId: patchPort
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/portIdInPath.yaml"
      requestBody:
        $ref: "./ports/portRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./ports/portResponse.yaml"
        "404":
          $ref: "./ports/errors/portNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    delete:
      tags:
        - ports
      summary: Delete a port by id
      operationId: deletePort
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/portIdInPath.yaml"
      responses:
        "200":
          $ref: "./ports/portResponse.yaml"
        "404":
          $ref: "./ports/errors/portNotFoundError.yaml"
  /servers/{serverId}/volumes:
    post:
      tags:
        - volumes
      summary: Create a new volume
      operationId: createEnvironmentVariable
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      requestBody:
        $ref: "./volumes/volumeRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./volumes/volumeResponse.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    get:
      tags:
        - volumes
      summary: Get Volumes of Server
      operationId: getVolume
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./volumes/volumeArrayResponse.yaml"
        "404":
          $ref: "./volumes/errors/volumeNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
  /servers/{serverId}/volumes/{volumeId}:
    get:
      tags:
        - volumes
      summary: Get a Volume by id
      operationId: getVolume
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/volumeIdInPath.yaml"
      responses:
        "200":
          $ref: "./volumes/volumeResponse.yaml"
        "404":
          $ref: "./volumes/errors/volumeNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    patch:
      tags:
        - volumes
      summary: Update a Volume by id
      operationId: patchVolume
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/volumeIdInPath.yaml"
      requestBody:
        $ref: "./volumes/volumeRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./volumes/volumeResponse.yaml"
        "404":
          $ref: "./volumes/errors/volumeNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    delete:
      tags:
        - volumes
      summary: Delete a Volume by id
      operationId: deleteVolume
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/volumeIdInPath.yaml"
      responses:
        "200":
          $ref: "./volumes/volumeResponse.yaml"
        "404":
          $ref: "./volumes/errors/volumeNotFoundError.yaml"
  /servers/{serverId}/environmentVariables:
    post:
      tags:
        - environmentVariables
      summary: Create a new environmentVariable
      operationId: createEnvironmentVariable
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      requestBody:
        $ref: "./environmentVariables/environmentVariableRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./environmentVariables/environmentVariableResponse.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    get:
      tags:
        - environmentVariables
      summary: Get EnvironmentVariables of Server
      operationId: getEnvironmentVariables
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./environmentVariables/environmentVariableArrayResponse.yaml"
        "404":
          $ref: "./environmentVariables/errors/environmentVariableNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
  /servers/{serverId}/environmentVariables/{environmentVariableId}:
    get:
      tags:
        - environmentVariables
      summary: Get a EnvironmentVariable by id
      operationId: getEnvironmentVariable
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/environmentVariableIdInPath.yaml"
      responses:
        "200":
          $ref: "./environmentVariables/environmentVariableResponse.yaml"
        "404":
          $ref: "./environmentVariables/errors/environmentVariableNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    patch:
      tags:
        - environmentVariables
      summary: Update a EnvironmentVariable by id
      operationId: patchEnvironmentVariable
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/environmentVariableIdInPath.yaml"
      requestBody:
        $ref: "./environmentVariables/environmentVariableRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./environmentVariables/environmentVariableResponse.yaml"
        "404":
          $ref: "./environmentVariables/errors/environmentVariableNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    delete:
      tags:
        - environmentVariables
      summary: Delete a EnvironmentVariable by id
      operationId: deleteEnvironmentVariable
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/environmentVariableIdInPath.yaml"
      responses:
        "200":
          $ref: "./environmentVariables/environmentVariableResponse.yaml"
        "404":
          $ref: "./environmentVariables/errors/environmentVariableNotFoundError.yaml"
  /servers/{serverId}/files:
    post:
      tags:
        - files
      summary: Create a new file
      description: This takes a base64 encoded file. An easy way to base64 encode a file with node is Buffer.from(fs.readFileSync('filename').toString()).toString('base64').
      operationId: createFile
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      requestBody:
        $ref: "./files/fileRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./files/fileResponse.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    get:
      tags:
        - files
      summary: Get Files of Server
      operationId: getFiles
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
      responses:
        "200":
          $ref: "./files/fileArrayResponse.yaml"
        "404":
          $ref: "./files/errors/fileNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
  /servers/{serverId}/files/{fileId}:
    get:
      tags:
        - files
      summary: Get a File by id
      operationId: getFile
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/fileIdInPath.yaml"
      responses:
        "200":
          $ref: "./files/fileResponse.yaml"
        "404":
          $ref: "./files/errors/fileNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    patch:
      tags:
        - files
      summary: Update a File by id
      operationId: patchFile
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/fileIdInPath.yaml"
      requestBody:
        $ref: "./files/fileRequest.yaml"
        required: true
      responses:
        "200":
          $ref: "./files/fileResponse.yaml"
        "404":
          $ref: "./files/errors/fileNotFoundError.yaml"
        "500":
          $ref: "./common/errors/internalServerError.yaml"
    delete:
      tags:
        - files
      summary: Delete a File by id
      operationId: deleteFile
      parameters:
        - $ref: "./common/serverIdInPath.yaml"
        - $ref: "./common/fileIdInPath.yaml"
      responses:
        "200":
          $ref: "./files/fileResponse.yaml"
        "404":
          $ref: "./files/errors/fileNotFoundError.yaml"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: authorization-key
    Owner:
      type: apiKey
      in: header
      name: owner
# Apply the API key globally to all operations
security:
  - ApiKeyAuth: []
  - Owner: []
